### ISSUE TITLE
Specter and GraalVM's native-image: unsupported?

### ISSUE THREAD

**Issue by DjebbZ** [nathanmarz/specter#271]
Hi,

I'm experimenting with the idea of having a specter-based tool to navigate data in the terminal. But the experimentation failed very quickly. Here's what I did:

`deps.edn`

``` clojure
{:paths   ["resources" "src"]
 :deps    {org.clojure/clojure   {:mvn/version "1.9.0"}
           com.rpl/specter       {:mvn/version "1.1.2"}
           org.clojure/tools.cli {:mvn/version "0.4.1"}}
 :aliases {:native-image {:extra-deps {clj.native-image
                                       {:git/url "https://github.com/taylorwood/clj.native-image.git"
                                        :sha     "d97f25aa153e0f94139f5d03e60a345151815d4d"}}
                          :main-opts  ["-m clj.native-image specter-cli.main"
                                       "-H:Name=specter"
                                       "--report-unsupported-elements-at-runtime"]
                          :jvm-opts   ["-Dclojure.compiler.direct-linking=true"]}
           :run          {:main-opts ["-m specter-cli.main"]}}}
```

`src/specter_cli/main.clj`

``` clojure
(ns specter-cli.main
  (:require [com.rpl.specter :as sp])
  (:gen-class))

(set! *warn-on-reflection* true)

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (sp/select sp/ALL [1 2 3]))
```

Then, following the instructions of https://github.com/taylorwood/clj.native-image I set the environment variable $GRAALVM_HOME to the folder where I unzipped the GraalVM's tools, then run `clj -A:native-image`.

Then running `./specter` produces this error:

```
Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Unresolved element found 
	at java.lang.Throwable.<init>(Throwable.java:265)
	at java.lang.Error.<init>(Error.java:70)
	at com.oracle.svm.core.jdk.UnsupportedFeatureError.<init>(UnsupportedFeatureError.java:31)
	at com.oracle.svm.core.jdk.Target_com_oracle_svm_core_util_VMError.unsupportedFeature(VMErrorSubstitutions.java:109)
	at com.oracle.svm.core.snippets.SnippetRuntime.unresolved(SnippetRuntime.java:206)
	at clojure.lang.Var.getRawRoot(Var.java:257)
	at specter_cli.main$_main$fn__3791.invoke(main.clj:10)
	at specter_cli.main$_main.invokeStatic(main.clj:10)
	at specter_cli.main$_main.doInvoke(main.clj:7)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at specter_cli.main.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
```

Maybe more useful is the error if I remove the flag ` "--report-unsupported-elements-at-runtime"` from the `:main-opts`:

```
error: Error loading a referenced type: java.lang.reflect.InvocationTargetException
Detailed message:
Error: Error loading a referenced type: java.lang.reflect.InvocationTargetException
Trace: 
	at parsing specter_cli.main$_main.invokeStatic(main.clj:10)
Call path from entry point to specter_cli.main$_main.invokeStatic(ISeq): 
	at specter_cli.main$_main.invokeStatic(main.clj:7)
	at specter_cli.main$_main.doInvoke(main.clj:7)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at specter_cli.main.main(Unknown Source)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:164)
	at com.oracle.svm.core.code.CEntryPointCallStubs.com_002eoracle_002esvm_002ecore_002eJavaMainWrapper_002erun_0028int_002corg_002egraalvm_002enativeimage_002ec_002etype_002eCCharPointerPointer_0029(generated:0)
Original exception that caused the problem: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.loadReferencedType(WrappedConstantPool.java:85)
	at com.oracle.svm.hosted.phases.SubstrateClassInitializationPlugin.loadReferencedType(SubstrateClassInitializationPlugin.java:70)
	at org.graalvm.compiler.java.BytecodeParser.maybeEagerlyResolve(BytecodeParser.java:3971)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.maybeEagerlyResolve(SharedGraphBuilderPhase.java:99)
	at org.graalvm.compiler.java.BytecodeParser.lookupMethod(BytecodeParser.java:3927)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1422)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.genInvokeStatic(SharedGraphBuilderPhase.java:168)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:4868)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3141)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:2950)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:888)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:782)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:95)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:204)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:323)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.flow.StaticInvokeTypeFlow.update(InvokeTypeFlow.java:346)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:508)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:174)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NoClassDefFoundError: com/rpl/specter/impl$magic_precompilation
	at jdk.vm.ci.hotspot.CompilerToVM.resolveTypeInPool(Native Method)
	at jdk.vm.ci.hotspot.HotSpotConstantPool.loadReferencedType(HotSpotConstantPool.java:700)
	... 33 more
Caused by: java.lang.ClassNotFoundException: com.rpl.specter.impl$magic_precompilation
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 35 more
```

It seems specter is using some kind of reflection that SubstrateVM (the native-image compiler) does not support. The GraalVM hopefully documents how to help SubstrateVM determines what kind of reflection is used (doc here: https://github.com/oracle/graal/blob/master/substratevm/REFLECTION.md).

I'm posting this here a personal reminder, but also in case anybody (including Nathan Marz) is interested and willing to provide some help/guidance.

Thanks in advance.

**Comment by nathanmarz** [comment]
`magic-precompilation` does an `eval`, so I'd suggest you'd start there to see if there's a conflict between `eval` and Graal.

Closing this issue because it seems more like a Graal issue than anything else. However, if you do find in your investigation that it is a Specter issue that can be addressed with a patch, feel free to re-open.

**Comment by DjebbZ** [comment]
Thanks for the pointer to `eval` Nathan.

**Comment by DjebbZ** [comment]
Indeed native-image doesn't support at all eval because eval dynamic
compile and load classes, a feature explicitly not supported by
native-image. Logic, it has to know in advance all the code it compiles.

I have several questions then:

- I'm wondering if there's a way to use specter without it doing eval. Am I
right if I say that some time ago (before 1.0 I think) specter functions
weren't compiling paths, and one had to use the `comp-*` versions of the
functions to have it compile paths, hence use `eval` underneath?

- Is it possible right now to use specter without `eval` ?

- If not, would you be interested in a contribution with "uncompiled"
version of the API, in order to explicitly support native-image? My
understanding is that it wouldn't make sense to use them in a JVM project
because of the performance degradation, but in a binary we don't really
care about this extra perf boost, we just want it to work.

**Comment by nathanmarz** [comment]
To avoid the codepaths that use `eval` avoid `path`, `select`, `transform`, `setval`, `multi-transform`. Instead, use `select*`, `transform*`,`setval*`, etc..

Without the `eval` codepaths, there's no way to do parameterized paths efficiently. For example:

```clj
(defn foo [a data]
  (select [(keypath a) ALL] data))
```

Thats efficient because of inline caching and eval. Replacing `select` with `select*` will still work, but you'll have a big performance hit due to the need to compile the path at every invocation. But since you don't mind the perf hit, it should work for you.

**Comment by DjebbZ** [comment]
Oh, this is very good news! Yeah the perf hit doesn't matter since it's for
a cli tool, so it will have to compile it by the way on each invocation.

Looking forward to try something. Will keep you updated.

And thanks again for your support.

**Comment by lvh** [comment]
For those looking at this issue at some point in the future: replacing all the non-starred specter calls with starred ones fixed the issue for me.
