### ISSUE TITLE
Lein uberjar classcast exception

### ISSUE THREAD

**Issue by atomic-hedgehog** [nathanmarz/specter#32]
I'm seeing a problem with building uberjars.  I'm testing with a minimal app made with `lein new app`.  `lein run` works fine, but `lein uberjar` fails with this exception:

`Caused by: java.lang.ClassCastException: com.rpl.specter.impl.TransformFunctions cannot be cast to com.rpl.specter.impl.TransformFunctions`

No one else seems to be having this issue so it's probably something I'm doing wrong.

The test machine details:
`CentOS 6.5 with openJDK 1.8.0_45`
`Leiningen 2.5.3 on Java 1.8.0_45 OpenJDK 64-Bit Server VM`

project.clj:
```clojure
(defproject spectertest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [com.rpl/specter  "0.8.0"]]
  :main ^:skip-aot spectertest.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

core.clj:
```clojure
(ns spectertest.core
  (:gen-class)
  (:require  [com.rpl.specter :refer :all] ))

(defn -main
  [& args]
  (prn
    (transform [(collect-one :hb) :status :service-status]
               +
               {:hb 1 :status { :service-status 3 }})))

```

The full exception stacktrace is:
```
Compiling spectertest.core                                                                                                                                                                                  [15/1015]
java.lang.ClassCastException: com.rpl.specter.impl.TransformFunctions cannot be cast to com.rpl.specter.impl.TransformFunctions, compiling:(specter.clj:138:10)
Exception in thread "main" java.lang.ClassCastException: com.rpl.specter.impl.TransformFunctions cannot be cast to com.rpl.specter.impl.TransformFunctions, compiling:(specter.clj:138:10)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3558)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:417)
        at clojure.lang.Compiler.compile1(Compiler.java:7226)
        at clojure.lang.Compiler.compile(Compiler.java:7292)
        at clojure.lang.RT.compile(RT.java:398)
        at clojure.lang.RT.load(RT.java:438)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
        at clojure.core$load_lib.doInvoke(core.clj:5485)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$load_libs.doInvoke(core.clj:5524)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invoke(core.clj:626)
        at clojure.core$require.doInvoke(core.clj:5607)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at spectertest.core$loading__4958__auto__.invoke(core.clj:1)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)
        at clojure.lang.Compiler.compile1(Compiler.java:7226)
        at clojure.lang.Compiler.compile1(Compiler.java:7216)
        at clojure.lang.Compiler.compile(Compiler.java:7292)
        at clojure.lang.RT.compile(RT.java:398)
        at clojure.lang.RT.load(RT.java:438)
        at clojure.lang.RT.load(RT.java:411)
        at clojure.core$load$fn__5066.invoke(core.clj:5641)
        at clojure.core$load.doInvoke(core.clj:5640)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invoke(core.clj:5446)
        at clojure.core$compile$fn__5071.invoke(core.clj:5652)
        at clojure.core$compile.invoke(core.clj:5651)
        at user$eval9$fn__18.invoke(form-init1749168943273755311.clj:1)
        at user$eval9.invoke(form-init1749168943273755311.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
Caused by: java.lang.ClassCastException: com.rpl.specter.impl.TransformFunctions cannot be cast to com.rpl.specter.impl.TransformFunctions
        at com.rpl.specter.impl$extype.invoke(impl.clj:238)
        at clojure.core$partition_by$fn__6373.invoke(core.clj:6613)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.core$seq.invoke(core.clj:133)
        at clojure.core$map$fn__4245.invoke(core.clj:2551)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        at clojure.lang.RT.seq(RT.java:484)
        at clojure.lang.RT.countFrom(RT.java:537)
        at clojure.lang.RT.count(RT.java:530)
        at com.rpl.specter.impl$fn__692.invoke(impl.clj:324)
        at com.rpl.specter.impl$fn__284$G__279__289.invoke(impl.clj:21)
        at com.rpl.specter$comp_paths.doInvoke(specter.clj:29)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3553)
        ... 51 more
Compilation failed: Subprocess failed
```

**Comment by michaelbarton** [comment]
I am seeing the same error, and I'm using 0.8.0

**Comment by michaelbarton** [comment]
This problem appears to go away when I switch to clojure 1.7.0

**Comment by atomic-hedgehog** [comment]
@michaelbarton Thanks! Upgrading our project to Clojure 1.7 resolved the issue for us.  That broke some other dependencies but they were outdated and bringing them up to current versions fixed everything.

**Comment by LusciousPear** [comment]
FYI,, I got this error with Clojure 1.8, but not 1.7.

**Comment by nathanmarz** [comment]
I was able to reproduce this and confirmed that upgrading to Clojure 1.7 solves the issue. Also checked with Clojure 1.8 which also works.
